### ISSUE TITLE
[FR] Translating by uploading PO files

### ISSUE THREAD

**Issue by SimonTil** [vsetka/deepl-translator#16]
Feature request:
I'm currently translating my third project with Poedit, but most of the times, Deepl already gave the perfect translation (with is great). Now I was thinking if you could add an option to upload PO (translation file) or POT (template for translation) files to Deepl to decrease the amount of work on translating projects.
The layout of a PO file is quite simple:

```
a few comment lines
msgid ""
msgstr ""
"a lot of nonsens about who made the translation, etc."

#: location/of/the/file.xxx:438 (line number)
msgid: "Phrase to translate"
msgstr: "Translated phrase"

#: location/of/the/file.xxx:465
msgid: "Phrase to translate"
msgstr: "Translated phrase"
etc.
```

Hope this will be implemented. My coding skills are fine for some Arduino stuff, but not good enough to write a script to automate this.

Regards,
Simon

**Comment by vsetka** [comment]
Repository not maintained
