### ISSUE TITLE
Request limit

### ISSUE THREAD

**Issue by lmfmaier** [vsetka/deepl-translator#5]
The API is currently limited. I still have to figure out if they put a hard limit on the absolute request count from an IP or are just limiting the number of requests within a certain timespan.

Error message: Server side error during DeepLy API call: HTTP code 429, message: "{"jsonrpc": "2.0","error":{"code":1042901,"message":"Too many requests."}}"

**Comment by vsetka** [comment]
I'll do some digging to come up with concrete numbers. Did this happen when translating a large file with many paragraphs perhaps?

The only thing I can do in the client is implement batching in the `translate` method and see if I can send one request for all paragraphs. Perhaps even a new method for batch translations of unrelated texts would make sense (ie `batchTranslate`) where all the texts would be sent in one request. You'd still have the same problem if translating too many batches in a shorter time span though.

I'll have experiment with the API and see what's possible.

**Comment by lmfmaier** [comment]
Hi, I did about 10.000 translations (ranging from simple strings to multiparagraph texts) and my IP address got hard limited. I think, there is an absolute hard limit on how many translations you can do from a single IP address. Maybe the have inroduced this recently, since they are about to release a commercial version of their Api shortly

**Comment by lmfmaier** [comment]
Btw: it doesn't matter if I user your Node module or the PHP wrapper "deepLy", the error is coming from their api.

**Comment by vsetka** [comment]
As I said, I'll see if I can put together a batch translation method, which should enable you to translate a much higher volume of text before hitting the rate limit threshold. However, this is only an assumption. It's possible that there is some level of limit on text items as well, in which case batching would not help.

I'll dig around and play some more with the API and see what's possible, but as you said, they plan on putting out a commercial API soon, so let's see where that goes.

**Comment by TheFive** [comment]
Hi, i just get this response now (december 2018) , on my production server and on my development server.

**Comment by vsetka** [comment]
> Hi, i just get this response now (december 2018) , on my production server and on my development server.

Hi @TheFive, I'll look into it today after work. Thanks for reporting.

**Comment by zdavatz** [comment]
Where can I specify my API key?
