### ISSUE TITLE
[BUG] Rate limit always hit

### ISSUE THREAD

**Issue by vsetka** [vsetka/deepl-translator#9]
## The problem

As reported [here](./5#issuecomment-448175074), all requests to the `jsonrpc` API are failing with
```
{
  "jsonrpc": "2.0",
  "error": { "code": 1042902, "message": "Too many requests." }
}
```
The problem is probably due to the same id being used in each request.

## What is the current behavior?

Any request for translation fails.

## What is the expected behavior?

Requests do not trigger rate limit IP blocks unless a specific client makes too many requests in a given time frame.

## Environment

All versions.

**Comment by 5t4rdu5t** [comment]
Same thing here `deepl-translator@1.2.1`

**Comment by 5t4rdu5t** [comment]
Anybody can point me the line where the id is maybe hardcoded please ?

**Comment by cocodrino** [comment]
hi @vsetka is possible resolve this issue or seems that this package can't work anymore?...seems that deepl did some change in their api :sob:

**Comment by vsetka** [comment]
Hey @cocodrino. I'd say it's most definitely possible to make it work again but it's not as trivial as just incrementing the `id` and adding a `timestamp` to requests. They seem to be using some heuristics to check if the traffic is coming from the website and blocking accordingly.

I only had a few hours last weekend for this project and the above mentioned didn't work. I plan to come back to it again but I won't have time for it until mid March perhaps. You are welcome to give it a shot yourself and submit a PR if you've found a way to make it work again but otherwise, you'll have to wait 🙂

**Comment by cocodrino** [comment]
thanks for the answer @vsetka , I think that they blocked that api, I had several weeks without use this api and now, at the first request I get this error, now I've tried several times and even I've tried using different ip's...but always I get the same error, seems that they remove the support for this free api and the error isn't so exactly what is happening...

**Comment by zdavatz** [comment]
Where can I specify my API key?

**Comment by vsetka** [comment]
You can't, that's never been implemented. This is not an official client library from deepL. It's something I've built for a personal project I don't use anymore and it relies on internal APIs (emulating what their website does).

**Comment by zdavatz** [comment]
Ok, good to know. Thank you.

**Comment by morsedl** [comment]
Perhaps you should mentioned all this on the github page? :-)

**Comment by GillesWHC** [comment]
I made a new [package](https://www.npmjs.com/package/deepl-client) in which you can use your own API key. Let me know if this works for you @morsedl

**Comment by vsetka** [comment]
Repository not maintained
